// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'MeetWave App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }
import { Inter } from 'next/font/google';
import './globals.css';


import Providers from './store/Features/page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'MeetWave App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
 
      <html lang="en">
      <body className={inter.className}
      >
        <Providers>
          {children}
        </Providers>
        </body>
      </html>

  );
};

export default RootLayout;